Repository pangeo-forge/pangeo-forge-recipes, pull requests merged in 2023-06, with the labels that each got.

#506 fix target chunks bug
  pangeo_forge_recipes/aggregation.py
  tests/test_aggregation.py
Labels: beam refactor

#527 Unused objects cleanup
  .github/workflows/main.yaml
  pangeo_forge_recipes/storage.py
  tests/conftest.py
  tests/test_storage.py
Labels: beam refactor

#521 Include merge dim positions in group keys emitted by `split_fragments`
  .gitignore
  pangeo_forge_recipes/rechunking.py
  tests/conftest.py
  tests/test_end_to_end.py
  tests/test_rechunking.py
Labels: release blocker

#490 Port of Terraclimate example to beam-refactor
  docs/pangeo_forge_recipes/tutorials/xarray_zarr/terraclimate.ipynb
Labels: beam refactor, release blocker
